### ISSUE TITLE
Information about generation of .blend generation file

### ISSUE THREAD

**Issue by Nicogene** [roboticslab-uc3m/teo-blender-models#1]
Hi!

In [iCubTech](https://github.com/icub-tech-iit) we are starting to explore the usage of animator/CG software for controlling our robots(in particular iCub).

In the past, we created a "mockup" plugin for commanding iCub from Maxxon Cinema4D(see https://github.com/robotology/c4d-icub-plugins).

How do you obtain the .blend file for your robot? Did you get it from the urdf/sdf?

It would be great if we can share some information about it, thanks!

**Comment by rsantos88** [comment]
Hi @Nicogene. First of all, thank you for your interest in this project. As in your case, I've created a [teo-robot-control](https://github.com/roboticslab-uc3m/teo-blender-models/blob/master/src/python/teo-robot-control.py) script for Blender (in the future it will be an installable plugin), adapted to the specific model of our robot. This script add a new panel within the Blender environment with controls and functionalities that act on our virtual model, allowing to move its joints or get its joint positions from the IK that Blender solves internally to animate its skeletons. 

The main interest of this is to be able to build complex trajectories with the Blender environment, either by creating them manually or by obtaining them from a MOCAP system and later exporting them to the robot. 

> How do you obtain the .blend file for your robot? Did you get it from the urdf/sdf?

First of all a clarification, the `.blend` files contain not only the 3D model of our robot. It's a project file created with Blender that can contain 3D mesh data, skeleton, lighting information, vertex painting, animation keyframes, NURBS objects, procedural textures, uv mapping design, and real-time interactivity data. Therefore, this file has been obtained through a successive work where elements have been incorporated. 

First, a full-scale 3D model of the robot was imported. This model in VRML V2.0 format was created in the robot design and only contains the 3D mesh with all the individual parts that make up the robot. Previously, replicated pieces were eliminated, some of these pieces were modified in dimensions or slightly remodeled. These loose pieces have been unified into objects that make up the limbs. A skeleton was created (what is known as "riggin" of a 3D character), a inverse kinematic was incorporated and  kinematic configuration with the joint limits of the robot. It was textured to give it a better appearance and finally, the script was developed to obtain the mentioned functionalities.

Currently only the skeleton of the upper part of the robot (trunk + arms) is finished but we are working on finishing the complete model including legs.

I hope it was helpful!

**Comment by Nicogene** [comment]
Hi @rsantos88,

It is very interesting, thank you a lot for the information, we kicked off recently this activity and as soon we will have some interesting result we will share it with the community!

I am closing this issue, thanks again.

**Comment by Nicogene** [comment]
Hi @rsantos88 !

as promised here is an update about our blender activities !
We recently made public our work on blender that you can find it here: https://github.com/robotology/blender-robotics-utils

That repo contains some [rigs of our robots](https://github.com/robotology/blender-robotics-utils#examples)

Those rigs has been obtained through  [a python script](https://github.com/robotology/blender-robotics-utils#urdftoblender) that from the urdf generates the rig .blend of the corresponding robot. It is robot-agnostic, it has some limitations explained in the [README](https://github.com/robotology/blender-robotics-utils#known-limitations).

Moreover we made a simple/demo controller, for moving the icub head accordingly to the animation made in blender (see [this video](https://github.com/robotology/blender-robotics-utils#icubneckblendercontroller-) 📹 )

If you have any question/curiosity you can contact me directly or open an issue in the repo!
