### ISSUE TITLE
Add info on Blender as a Python module

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-blender-models#4]
Add info on Blender as a Python module (via Docker by @imontesino ).

**Comment by imontesino** [comment]
Here is the repo for a library using blender as an engine for mathematical plots.
[blender-plotting](https://github.com/imontesino/blender-plotting)

The Readme has instructions on creating the docker file to build the `bpy` module and/or using it in the docker.

**Comment by jgvictores** [comment]
Closing via https://github.com/roboticslab-uc3m/teo-blender-models/commit/e6befe7a29905bce541f276ff877aa5c8b973f6e thanks!
